### ISSUE TITLE
House Theme Disappears when login back to the game.

### ISSUE THREAD

**Issue by OfficialMisuki** [ZeruLight/Erupe#92]
**Description**:
House Themes (in S.U 9.2) just disappears when you log out after setting a theme then exiting the game at any time, leaving only your item box, rastas, cats and waitress floating on a jungle(?)
Themes are also required to be bought back again if purchased previously.

**Reproduction Steps**:
1. Download the "savemercenary.bin" linked below and apply it to your character using save editor (I've used Chakratos Save Manager)
2. After login in the game normally, go to your house and buy the "Ice Cave/Tunnel" theme.
3. Apply "Ice Cave/Tunnel" theme to your house.
4. Exit the house then do a couple of hunts
5. Exit the game
6. Log back to the game and check the house.

**Screenshots**
![image](https://github.com/ZeruLight/Erupe/assets/91129187/7fc38193-5582-4e54-a8a4-9a92068e308e)

**Additional context**
- My saved was previously bugged where "Point Exchange" does not work from the tore manager, that's why I was given a "clean" savemercenary.bin to have that bug fixed.
- However, after that, my house theme just keeps disappearing after applying the clean "savemercenary.bin" file ([Download link here](https://discord.com/channels/368424389416583169/926651887153987614/1165666893709983805), straight from PewPewDojo server)

**Comment by matthe815** [comment]
This appears to have been fixed with the work going into 9.3 however I will do some more testing.

**Comment by sekaiwish** [comment]
It still happens to me occasionally but I've never been able to find any specific trigger. Might be able to just scan the values and cancel saving if any are <0?
